/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pontoEletronico.frames;

import br.com.pontoEletronico.intefaces.AbstractJFrame;
import br.com.pontoEletronico.intefaces.ListenerAbstractDefaultAdapter;
import br.com.pontoEletronico.tablemodels.TableModelDefaultAdapter;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Optional;
import javax.swing.JButton;
import javax.swing.RowFilter;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ALMEIDA
 */
public final class Form_PesquisaDefault extends AbstractJFrame {

    private static final long serialVersionUID = 8289616995829836221L;
    private final Listener_Form_PesquisaDefault listener;
    private TableRowSorter sorter;
    private TableModelDefaultAdapter model;
    private ListenerAbstractDefaultAdapter listener_solicitante;

    /**
     * Creates new form lista_funcionario
     */
    public Form_PesquisaDefault(TableModelDefaultAdapter model, ListenerAbstractDefaultAdapter listener_solicitante) {
        setImageIcon();
        initComponents();
        this.model = model;
        this.listener_solicitante = listener_solicitante;
        listener = new Listener_Form_PesquisaDefault(this);
    }

    @Override
    public Optional<List<JButton>> getListButtons() {
        return Optional.empty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        painelMain = new javax.swing.JPanel();
        cbPesquisa = new javax.swing.JComboBox<>();
        txtPesquisa = new javax.swing.JTextField();
        scPesquisa = new javax.swing.JScrollPane();
        tbPesquisa = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar");

        cbPesquisa.setPreferredSize(new java.awt.Dimension(160, 23));

        txtPesquisa.setPreferredSize(new java.awt.Dimension(279, 23));

        tbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scPesquisa.setViewportView(tbPesquisa);

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMainLayout.createSequentialGroup()
                        .addComponent(cbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(scPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPesquisa;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel painelMain;
    private javax.swing.JScrollPane scPesquisa;
    private javax.swing.JTable tbPesquisa;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    public final class Listener_Form_PesquisaDefault extends ListenerAbstractDefaultAdapter<Form_PesquisaDefault> implements CaretListener {

        private static final long serialVersionUID = -6231853840734766279L;

        public Listener_Form_PesquisaDefault(Form_PesquisaDefault form) {
            super(form);
            initComponents();
        }

        @Override
        protected void initComponents() {
            super.initComponents();
            addModel();
        }

        @Override
        protected void attachListener() {
            super.attachListener();
            txtPesquisa.addCaretListener(this);
            tbPesquisa.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (e.getClickCount() == 2) {
                        listener_solicitante.setObject(model.getObject(sorter.convertRowIndexToModel(tbPesquisa.getSelectedRow())));
                        dispose();
                    }
                }
            });
        }

        @Override
        public void caretUpdate(CaretEvent e) {
            if (e.getMark() > 0) {
                sorter.setRowFilter(RowFilter.regexFilter("^(?i:.*" + txtPesquisa.getText() + ".*)$", cbPesquisa.getSelectedIndex()));
            } else {
                sorter.setRowFilter(null);
            }
        }

        public void addModel() {
            sorter = new TableRowSorter(model);
            tbPesquisa.setModel(model);
            tbPesquisa.setRowSorter(sorter);
            for (int c = 0; c < model.getColumnCount(); c++) {
                cbPesquisa.addItem(model.getColumnName(c));
            }
        }

    }

}
